unit Geral.Model.SeloSituacao;

interface

const
  CG_SELO_SITUACAO_ID_DISPONIVEL = 1;
  CG_SELO_SITUACAO_ID_UTILIZADO = 2;
  CG_SELO_SITUACAO_ID_EXTRAVIADO = 3;
  CG_SELO_SITUACAO_ID_INUTILIZADO = 4;
  CG_SELO_SITUACAO_ID_DEVOLVIDO = 5;
  CG_SELO_SITUACAO_ID_PERDIDO = 7;

implementation

end.
